"""add contact link to products

Revision ID: 5999a7384b8a
Revises: d254ff4ea0ba
Create Date: 2026-10-04 19:31:43.397449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5999a7384b8a'
down_revision: Union[str, Sequence[str], None] = 'd254ff4ea0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('contact_link', sa.String(length=500), nullable=True))

    op.execute(
        """
        UPDATE products
        SET contact_link = 'https://www.facebook.com/zxhuen'
        WHERE contact_link IS NULL
        """
    )

    op.alter_column(
        "products",
        "contact_link",
        existing_type=sa.String(500),
        nullable=False,
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'contact_link')
    # ### end Alembic commands ###
