"""chat session's session == not unique anymore

Revision ID: 67de2f1b838c
Revises: 839294b4cb04
Create Date: 2026-08-08 17:01:14.157485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67de2f1b838c'
down_revision: Union[str, Sequence[str], None] = '839294b4cb04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_sessions_session_token_key'), 'chat_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('chat_sessions_session_token_key'), 'chat_sessions', ['session_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
