"""added unique constraint on chat session model

Revision ID: a096a0eb270a
Revises: 088fbce286a7
Create Date: 2026-08-14 13:51:35.442959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a096a0eb270a'
down_revision: Union[str, Sequence[str], None] = '088fbce286a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chat_session_product_token', 'chat_sessions', ['product_id', 'session_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat_session_product_token', 'chat_sessions', type_='unique')
    # ### end Alembic commands ###
