"""added index true on chat session's session token for better retrieval

Revision ID: d254ff4ea0ba
Revises: a096a0eb270a
Create Date: 2026-08-16 14:18:02.689813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd254ff4ea0ba'
down_revision: Union[str, Sequence[str], None] = 'a096a0eb270a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_sessions_session_token'), 'chat_sessions', ['session_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_session_token'), table_name='chat_sessions')
    # ### end Alembic commands ###
