"""added user usage model

Revision ID: dfc74d715d27
Revises: 9411f3c6054e
Create Date: 2026-08-04 18:11:56.934219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc74d715d27'
down_revision: Union[str, Sequence[str], None] = '9411f3c6054e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_usages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('products_created_today', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_usages')
    # ### end Alembic commands ###
